### PR TITLE
Fix checkbox auto unchecked issue

### LINKED ISSUE #23: Data changes not saved in review mode

### PR DESCRIPTION
**Pull request by victoria34**
Fix #23

### CODE REVIEW

File: app/scripts/directives/realtimestring.js [hunk 1]
```diff
@@ -204,9 +204,17 @@ angular.module('oncokbApp')
                         $scope.diffHTML = mainUtils.calculateDiff($scope.data[$scope.key + '_review'].lastReviewed, $scope.data[$scope.key]);
                     }
                 };
-                $scope.toggleCheckbox = function () {
-                    if ($scope.data[$scope.key] === $scope.pureContent.text && $scope.data[$scope.key] !== '') {
-                        $scope.pureContent.text = '';
+                $scope.toggleCheckbox = function (e) {
+                    if ($scope.t === 'radio') {
+                        if ($scope.data[$scope.key] === e.target.value) {
+                            $scope.pureContent.text = '';
```
Comment (zhx828) [inline app/scripts/directives/realtimestring.js]: For any value does not match the `$scope.data[$scope.key]`, pureContent.text will never get assigned. What's the use case of that? Should that be handled?

File: app/views/gene.html [hunk 2]
```diff
@@ -150,12 +150,12 @@ <h3>Background:
             <div class="panelContent" id="{{mutation.mutation_effect_uuid}}">
               <p ng-show="displayPrecisely(mutation.mutation_effect.oncogenic_uuid)">
                 <strong style="float: left; margin-right: 5px;">Oncogenic:</strong>
-                <realtime-string t="'checkbox'" key="'oncogenic'" path="effectPath" checkboxes="checkboxes['oncogenic']" uuid="getUUID({type: 'mutation_effect', key: 'oncogenic', path: path})"></realtime-string>
```
Comment (zhx828) [inline app/views/gene.html]: For radio, we can never deselect the options anymore. I don't think that's our intension. For instance, you may not want to select any oncogenicity for `Oncogenic Mutations`. But if the curator accidentally chooses one, there is no way to revert back.

File: app/scripts/directives/realtimestring.js (hunk 1 above)
Comment (victoria34) [reply app/scripts/directives/realtimestring.js]: We don't need to handle it. `$scope.data[$scope.key] === e.target.value` means the checkbox is already checked and we want to uncheck it. Otherwise, `$scope.pureContent.text` is equal to selected checkbox.value.

File: app/views/gene.html (hunk 2 above)
Comment (victoria34) [reply app/views/gene.html]: We can revert it back but I have to do that programmatically. I use radio because it fits the case that only choose at most 1 checkbox in a checkbox group.

File: app/scripts/directives/realtimestring.js (hunk 1 above)
Comment (zhx828) [reply app/scripts/directives/realtimestring.js]: Oh I see. Here is where you set the value to empty when user double clicks on the radio.
