### PR TITLE
Fix cursor jumping issue

### LINKED ISSUE #12: Cursor jumping issue
Cursor jumps to beginning of a paragraph after copy and paste content.

### PR DESCRIPTION
**Pull request by victoria34**
Fix #12 
1. Replace `<p contenteditable>` by `<textarea>` to avoid cursor jumping.
2. Replace watch(data[key]) by ng-change to avoid that updatedBy is messed up.
3. No movingFlag anymore. Moving mutations won't cause any data changes in review mode.

### CODE REVIEW

File: app/scripts/controllers/gene.js [hunk 1]
```diff
@@ -471,14 +469,7 @@ angular.module('oncokbApp')
...
             function isChangedSection(uuids) {
-                var result = false;
-                _.some(uuids, function (uuid) {
-                    if (uuid && $scope.geneMeta.review[uuid]) {
-                        result = true;
-                        return true;
-                    }
-                });
-                return result;
+                return _.intersection(uuids, _.keys($scope.geneMeta.review)).length > 0;
```
Comment (zhx828) [inline app/scripts/controllers/gene.js]: I would not use intersection over some. It has worse performance.

File: app/scripts/controllers/gene.js [hunk 2]
```diff
@@ -3595,12 +3580,8 @@ angular.module('oncokbApp')
                 if (_.isUndefined(data.tumorRef.cancerTypes_review)) {
                     data.tumorRef.cancerTypes_review = {};
                 }
-                if (_.isUndefined(data.tumorRef.cancerTypes_review.updatedBy)) {
```
Comment (zhx828) [inline app/scripts/controllers/gene.js]: Why did we remove these checks?

File: app/scripts/directives/realtimestring.js [hunk 3]
```diff
@@ -165,10 +94,17 @@ angular.module('oncokbApp')
...
                         }
+                        // Assign new value to scope.data[scope.key] to update content to gene page when multiple editing at the same time.
+                        if (scope.data[scope.key] !== scope.pureContent.text && !isPropagation) {
+                            scope.data[scope.key] = scope.pureContent.text;
+                        }
                     }
                 }
             },
             controller: function ($scope) {
+                $scope.pureContent = {
```
Comment (zhx828) [inline app/scripts/directives/realtimestring.js]: Why bother to create an object with one property only?

File: app/styles/main.scss [hunk 4]
```diff
@@ -1119,3 +1094,56 @@ input[type=radio]:checked + label:before, input[type=checkbox]:checked + label:b
...
+    font-style:italic;
+    margin-top:-30px;
+    margin-left:30%;
+    color:orange
+  }
+  .treatment-name {
+    height:auto;
+  }
+}
+.summary-bottom {
```
Comment (zhx828) [inline app/styles/main.scss]: Not necessary to create a class with one property unless the class is enabled with a condition. The same applies to margin-bottom-0

File: app/scripts/directives/realtimestring.js [hunk 5]
```diff
@@ -353,25 +277,55 @@ angular.module('oncokbApp')
...
+                        }
+                        if ($scope.t === 'p' || $scope.t === 'short') {
+                            $timeout.cancel($scope.timeoutRef);
+                            if ($scope.fe === true && !$scope.data[$scope.key+'_editing']) {
+                                $scope.data[$scope.key+'_editing'] = $rootScope.me.name;
+                            }
+                            $scope.timeoutRef = $timeout(function() {
+                                delete $scope.data[$scope.key+'_editing'];
+                                $scope.initializeFE();
+                            }, 10*1000);
```
Comment (zhx828) [inline app/scripts/directives/realtimestring.js]: 10s seems quite long time. What's the consideration here?

Comment (victoria34) [reply app/scripts/directives/realtimestring.js]: I didn't change the time. It's set by Jiaojiao. I can reduce the time and test on it if you want.

File: app/styles/main.scss (hunk 4 above)
Comment (victoria34) [reply app/styles/main.scss]: I don't want to write css in html and also this class will be used at multiple places

File: app/scripts/directives/realtimestring.js (hunk 3 above)
Comment (victoria34) [reply app/scripts/directives/realtimestring.js]: This is a well-known issue that ng-model cannot monitor the data change. In this case, it doesn't work if you bind to scope.purecontent(string), but it works when you bind to  scope.purecontent.text(object). It's weird but it's true.

File: app/scripts/controllers/gene.js (hunk 2 above)
Comment (victoria34) [reply app/scripts/controllers/gene.js]: In this case, it won't record the updatedBy and updateTime after first initialization.

File: app/scripts/controllers/gene.js (hunk 1 above)
Comment (victoria34) [reply app/scripts/controllers/gene.js]: I'll roll it back.
